services:
  mysql:
    image: mysql:8.0
    container_name: bibliosystem-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibliosystem
    ports:
      - "3306:3306"
    volumes:
      - ./banco_dados/bibliosystem.sql:/docker-entrypoint-initdb.d/bibliosystem.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: